[versions]
# Core versions
agp = "9.0.0"
coreSplashscreen = "1.2.0"
kotlin = "2.3.0"
androidxCore = "1.17.0"
lifecycle = "2.10.0"
composeBom = "2026.01.00"
lifecycleProcess = "2.10.0"
lifecycleProcessVersion = "2.10.0"
materialIconsExtended = "1.7.8"
room = "2.8.4"
firebaseBom = "34.8.0"
ksp = "2.3.4"
material3 = "1.13.0"
googleMaterial = "1.13.0"
runtimeLivedata = "1.10.1"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
# AndroidX
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.12.2" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version = "2.9.6" }
androidx-compose-animation-core = { group = "androidx.compose.animation", name = "animation-core" }

# Database

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-database = { group = "com.google.firebase", name = "firebase-database" }

# Others
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.10.2" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.13.2" }
junit = { group = "junit", name = "junit", version = "4.13.2" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }

google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
